var parameters = {
   "params":{
      "param":[
         {
            "code":"0c",
            "aws":"AccountReference"
         },
         {
            "code":"0d",
            "aws":"TransactionComment"
         },
         {
            "code":"1a",
            "aws":"Type"
         },
         {
            "code":"1b",
            "aws":"Comments"
         },
         {
            "code":"2a",
            "aws":"Domain/DomainName"
         },
         {
            "code":"2b",
            "aws":"Domain/RegPeriod"
         },
         {
            "code":"2c",
            "aws":"Domain/EncodingType"
         },
         {
            "code":"2d",
            "aws":"Domain/DomainHandle"
         },
         {
            "code":"2f",
            "aws":"Domain/AuthInfo"
         },
         {
            "code":"20b",
            "aws":"Domain/DomainPurpose"
         },
         {
            "code":"2n",
            "aws":"Domain/LocalPresence"
         },
         {
            "code":"3a",
            "aws":"Domain/Registrant/Name"
         },
         {
            "code":"3b",
            "aws":"Domain/Registrant/Name"
         },
         {
            "code":"3c",
            "aws":"Domain/Registrant/OrgName"
         },
         {
            "code":"3d",
            "aws":"Domain/Registrant/Address1"
         },
         {
            "code":"3e",
            "aws":"Domain/Registrant/Address2"
         },
         {
            "code":"3f",
            "aws":"Domain/Registrant/City"
         },
         {
            "code":"3g",
            "aws":"Domain/Registrant/State"
         },
         {
            "code":"3h",
            "aws":"Domain/Registrant/PostalCode"
         },
         {
            "code":"3i",
            "aws":"Domain/Registrant/CountryCode"
         },
         {
            "code":"3j",
            "aws":"Domain/Registrant/Phone"
         },
         {
            "code":"3k",
            "aws":"Domain/Registrant/Fax"
         },
         {
            "code":"3l",
            "aws":"Domain/Registrant/Email"
         },
         {
            "code":"3m",
            "aws":"Domain/Registrant/RegistrantNumber"
         },
         {
            "code":"3p",
            "aws":"Domain/Registrant/VatNumber"
         },
         {
            "code":"3q",
            "aws":"Domain/Registrant/RegistrantType"
         },
         {
            "code":"3s",
            "aws":"Domain/Registrant/Details"
         },
         {
            "code":"20a",
            "aws":"Domain/Registrant/NexusCategory"
         },
         {
            "code":"4a",
            "aws":"Domain/AdminContact/Handle"
         },
         {
            "code":"4b",
            "aws":"Domain/AdminContact/FirstName"
         },
         {
            "code":"4c",
            "aws":"Domain/AdminContact/LastName"
         },
         {
            "code":"4d",
            "aws":"Domain/AdminContact/OrgName"
         },
         {
            "code":"4e",
            "aws":"Domain/AdminContact/Address1"
         },
         {
            "code":"4f",
            "aws":"Domain/AdminContact/Address2"
         },
         {
            "code":"4g",
            "aws":"Domain/AdminContact/City"
         },
         {
            "code":"4h",
            "aws":"Domain/AdminContact/State"
         },
         {
            "code":"4i",
            "aws":"Domain/AdminContact/PostalCode"
         },
         {
            "code":"4j",
            "aws":"Domain/AdminContact/CountryCode"
         },
         {
            "code":"4k",
            "aws":"Domain/AdminContact/Phone"
         },
         {
            "code":"4l",
            "aws":"Domain/AdminContact/Fax"
         },
         {
            "code":"4m",
            "aws":"Domain/AdminContact/Email"
         },
         {
            "code":"4n",
            "aws":"Domain/AdminContact/OrganisationNumber"
         },
         {
            "code":"4o",
            "aws":"Domain/AdminContact/Type"
         },
         {
            "code":"4p",
            "aws":"Domain/AdminContact/Details"
         },
         {
            "code":"5a",
            "aws":"Domain/TechContact/Handle"
         },
         {
            "code":"5b",
            "aws":"Domain/TechContact/FirstName"
         },
         {
            "code":"5c",
            "aws":"Domain/TechContact/LastName"
         },
         {
            "code":"5d",
            "aws":"Domain/TechContact/OrgName"
         },
         {
            "code":"5e",
            "aws":"Domain/TechContact/Address1"
         },
         {
            "code":"5f",
            "aws":"Domain/TechContact/Address2"
         },
         {
            "code":"5g",
            "aws":"Domain/TechContact/City"
         },
         {
            "code":"5h",
            "aws":"Domain/TechContact/State"
         },
         {
            "code":"5i",
            "aws":"Domain/TechContact/PostalCode"
         },
         {
            "code":"5j",
            "aws":"Domain/TechContact/CountryCode"
         },
         {
            "code":"5k",
            "aws":"Domain/TechContact/Phone"
         },
         {
            "code":"5l",
            "aws":"Domain/TechContact/Fax"
         },
         {
            "code":"5m",
            "aws":"Domain/TechContact/Email"
         },
         {
            "code":"5n",
            "aws":"Domain/TechContact/OrganisationNumber"
         },
         {
            "code":"5o",
            "aws":"Domain/TechContact/Type"
         },
         {
            "code":"5p",
            "aws":"Domain/TechContact/Details"
         },
         {
            "code":"6a",
            "aws":"Domain/BillingContact/Handle"
         },
         {
            "code":"6b",
            "aws":"Domain/BillingContact/FirstName"
         },
         {
            "code":"6c",
            "aws":"Domain/BillingContact/LastName"
         },
         {
            "code":"6d",
            "aws":"Domain/BillingContact/OrgName"
         },
         {
            "code":"6e",
            "aws":"Domain/BillingContact/Address1"
         },
         {
            "code":"6f",
            "aws":"Domain/BillingContact/Address2"
         },
         {
            "code":"6g",
            "aws":"Domain/BillingContact/City"
         },
         {
            "code":"6h",
            "aws":"Domain/BillingContact/State"
         },
         {
            "code":"6i",
            "aws":"Domain/BillingContact/PostalCode"
         },
         {
            "code":"6j",
            "aws":"Domain/BillingContact/CountryCode"
         },
         {
            "code":"6k",
            "aws":"Domain/BillingContact/Phone"
         },
         {
            "code":"6l",
            "aws":"Domain/BillingContact/Fax"
         },
         {
            "code":"6m",
            "aws":"Domain/BillingContact/Email"
         },
         {
            "code":"6n",
            "aws":"Domain/BillingContact/OrganisationNumber"
         },
         {
            "code":"6o",
            "aws":"Domain/BillingContact/Type"
         },
         {
            "code":"6p",
            "aws":"Domain/BillingContact/Details"
         },
         {
            "code":"7a",
            "aws":"Domain/NameServers/NameServer1/HostName"
         },
         {
            "code":"7b",
            "aws":"Domain/NameServers/NameServer1/IpAddress"
         },
         {
            "code":"8a",
            "aws":"Domain/NameServers/NameServer2/HostName"
         },
         {
            "code":"8b",
            "aws":"Domain/NameServers/NameServer2/IpAddress"
         },
         {
            "code":"8a.1",
            "aws":"Domain/NameServers/NameServer3/HostName"
         },
         {
            "code":"8b.1",
            "aws":"Domain/NameServers/NameServer3/IpAddress"
         },
         {
            "code":"8a.2",
            "aws":"Domain/NameServers/NameServer4/HostName"
         },
         {
            "code":"8b.2",
            "aws":"Domain/NameServers/NameServer4/IpAddress"
         },
         {
            "code":"8a.3",
            "aws":"Domain/NameServers/NameServer5/HostName"
         },
         {
            "code":"8b.3",
            "aws":"Domain/NameServers/NameServer5/IpAddress"
         },
         {
            "code":"8a.4",
            "aws":"Domain/NameServers/NameServer6/HostName"
         },
         {
            "code":"8b.4",
            "aws":"Domain/NameServers/NameServer6/IpAddress"
         },
         {
            "code":"8a.5",
            "aws":"Domain/NameServers/NameServer7/HostName"
         },
         {
            "code":"8b.5",
            "aws":"Domain/NameServers/NameServer7/IpAddress"
         },
         {
            "code":"8a.6",
            "aws":"Domain/NameServers/NameServer8/HostName"
         },
         {
            "code":"8b.6",
            "aws":"Domain/NameServers/NameServer8/IpAddress"
         },
         {
            "code":"8a.7",
            "aws":"Domain/NameServers/NameServer9/HostName"
         },
         {
            "code":"8b.7",
            "aws":"Domain/NameServers/NameServer9/IpAddress"
         },
         {
            "code":"8a.8",
            "aws":"Domain/NameServers/NameServer10/HostName"
         },
         {
            "code":"8b.8",
            "aws":"Domain/NameServers/NameServer10/IpAddress"
         },
         {
            "code":"8a.9",
            "aws":"Domain/NameServers/NameServer11/HostName"
         },
         {
            "code":"8b.9",
            "aws":"Domain/NameServers/NameServer11/IpAddress"
         },
         {
            "code":"8a.10",
            "aws":"Domain/NameServers/NameServer12/HostName"
         },
         {
            "code":"8b.10",
            "aws":"Domain/NameServers/NameServer12/IpAddress"
         },
         {
            "code":"8a.11",
            "aws":"Domain/NameServers/NameServer13/HostName"
         },
         {
            "code":"8b.11",
            "aws":"Domain/NameServers/NameServer13/IpAddress"
         },
         {
            "code":"25a",
            "aws":"Domain/TradeMark/Name"
         },
         {
            "code":"25b",
            "aws":"Domain/TradeMark/Country"
         },
         {
            "code":"25c",
            "aws":"Domain/TradeMark/Date"
         },
         {
            "code":"25d",
            "aws":"Domain/TradeMark/Number"
         },
         {
            "code":"25e",
            "aws":"Domain/TradeMark/Type"
         },
         {
            "code":"25f",
            "aws":"Domain/TradeMark/Contact"
         },
         {
            "code":"25h",
            "aws":"Domain/TradeMark/ContactLanguage"
         },
         {
            "code":"25g",
            "aws":"Domain/TradeMark/DocumentationLanguage"
         },
         {
            "code":"25i",
            "aws":"Domain/TradeMark/SecondContact"
         },
         {
            "code":"25j",
            "aws":"Domain/TradeMark/ThirdContact"
         },
         {
            "code":"25k",
            "aws":"Domain/TradeMark/RegDate"
         }
      ]
   },
   "types":{
      "type":[
         {
            "mail":"NEW",
            "mail_short":"N",
            "aws":"Register_Domain"
         },
         {
            "mail":"QUEUE",
            "mail_short":"Q",
            "aws":"Queue_Domain"
         },
         {
            "mail":"RENEW",
            "mail_short":"R",
            "aws":"Renew_Domain"
         },
         {
            "mail":"EXPIRE",
            "mail_short":"E",
            "aws":"Expire_Domain"
         },
         {
            "mail":"UNEXPIRE",
            "mail_short":"U",
            "aws":"Unexpire_Domain"
         },
         {
            "mail":"UNEXPIRE",
            "aws":"Unexpire_Domain"
         },
         {
            "mail":"DEQUEUE",
            "aws":"DeQueue"
         },
         {
            "mail":"TRANSFER",
            "aws":"Transfer_Domain"
         },
         {
            "mail":"DELETE",
            "aws":"Delete_Domain"
         },
         {
            "mail":"CONTACT UPDATE",
            "aws":"Contact_Update"
         },
         {
            "mail":"NS UPDATE",
            "aws":"Nameserver_Update"
         },
         {
            "mail":"REGISTRANT UPDATE",
            "aws":"Owner_Change"
         },
         {
            "mail":"CHANGE LOCKS",
            "aws":"Change_Locks"
         },
         {
            "mail":"DOMAIN DETAILS UPDATE",
            "aws":"Domain_Details_Update"
         },
         {
            "mail":"REGISTRANT DETAILS UPDATE",
            "aws":"Registrant_Details_Update"
         }
      ]
   }
}
var orderParams = {};
var orderTypes = {};
parameters.params.param.forEach(function(param) {
   orderParams[param.code]=param;
})
parameters.types.type.forEach(function(type) {
   orderTypes[type.mail] = type; 
})
parameters.types.type.forEach(function(type) {
   if(type.mail_short) orderTypes[type.mail_short] = type; 
})
module.exports.orderParams = orderParams;
module.exports.orderTypes  = orderTypes;
